### ISSUE TITLE
CCT Diagram

### ISSUE THREAD

**Issue by jackjhill** [collin80/DueMotorCtrl#1]
Hello Colin,

This isn't really an issue, but I couldn't find any other way to contact you regarding dueMotorCtrl.  Was wondering if you have available a circuit diagram or similar that supports how the applications works?

Regards,

Jack

**Comment by collin80** [comment]
Sorry, the source ended up being open source but the whole rest of the design was closed up so really all I've got to offer is the source code you see here.

**Comment by jackjhill** [comment]
Thanks for getting back to me Collin - appreciate it.  If I keep it to a practical minimum, do you mind if I quiz you on this from time-to-time?  No probs if you're too busy.
